version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  scraper:
    build:
      context: .
      dockerfile: scraper/Dockerfile  
    container_name: scraper
    depends_on:
      - mongo
    volumes:
      - .:/app  
    working_dir: /app/scraper  
    command: python import_mongo.py  

  rag:
    build:
      context: .
      dockerfile: RAG/Dockerfile
    container_name: rag
    depends_on:
      - mongo
      - scraper
    ports:
      - "9081:9081"
    working_dir: /app/RAG
    volumes:
      - .:/app                      
    command: /bin/bash -c "sleep 10 && python RAGMultimodal.py"
    environment:
      - API_KEY=JpQAceF80Htu21tCbZx8eZGhye2UP2V
      - BASE_URL=http://rag:9081
      - MONGO_HOST=mongo               # Connexion à Mongo depuis le conteneur

volumes:
  mongo_data: