services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  scraper:
    build: .
    container_name: scraper
    depends_on:
      - mongo
    volumes:
      - .:/app